ci: command

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,8 +9,6 @@ jobs:
     env:
       SSH_TARGET: 54.206.53.213  # main branch deploy target
       SSH_DEV_TARGET: 54.206.53.213  # develop branch deploy target
-      SSH_KEY: ${{ secrets.SSH_KEY_DEV }} # main branch SSH key
-      SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }} # develop branch SSH key
       NODE_ENV: production
 
     steps:
@@ -30,26 +28,21 @@ jobs:
             echo "Using develop branch SSH target"
             echo "SSH_TARGET=$SSH_DEV_TARGET" >> $GITHUB_ENV
           fi
-      - name: Set SSH key based on branch
-        run: |
-          if [ "${{ steps.branch.outputs.branch }}" == "main" ]; then
-            echo "Using main branch SSH key"
-            echo "SSH_KEY=SSH_KEY" >> $GITHUB_ENV
-          elif [ "${{ steps.branch.outputs.branch }}" == "develop" ]; then
-            echo "Using develop branch SSH key"
-            echo "SSH_KEY=SSH_KEY_DEV" >> $GITHUB_ENV
-          fi
 
       - name: Set up SSH
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_KEY_DEV }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
+          if [ "${{ steps.branch.outputs.branch }}" == "main" ]; then
+            echo "${{ secrets.SSH_KEY }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
+          elif [ "${{ steps.branch.outputs.branch }}" == "develop" ]; then
+            echo "${{ secrets.SSH_KEY_DEV }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
+          fi
           chmod 600 ~/.ssh/id_rsa.pem  # set the permissions
           ssh-keyscan "$SSH_TARGET" >> ~/.ssh/known_hosts  # add the host to the known_hosts file
           chmod 644 ~/.ssh/known_hosts  # set the permissions
 
       - name: Deploy to EC2
         run: |
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && git pull origin ${{ steps.branch.outputs.branch }}"
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && pnpm install && pnpm run build"
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && pm2 restart 0"
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && git fetch && git reset --hard origin/${{ steps.branch.outputs.branch }}" || { echo "Failed to execute the git command"; exit 1; }
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && pnpm install && pnpm run build" || { echo "Failed to execute the build command"; exit 1; }
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd AppFlowy-Website && node run-script.js" || { echo "Failed to execute the start command"; exit 1; }
